### ISSUE TITLE
Some install errors?

### ISSUE THREAD

**Issue by shadowdevnotreal** [whiterabb17/sifter#1]
Excuse my stupidity.
I got a few errors on install and it randomly asks for my git username and pass.
I realized I had to make a call to the API and use my OATH token, but I didn't so that until after the install started.
PLEASE tell me what I am doing wrong, because this is a cool tool I would like to test and promote for you.

**Comment by whiterabb17** [comment]
Nothing your doing wrong, some repos were on my last account which unfortunately was closed so the repos were lost.
Ill try correct the errors in the next few days

**Comment by shadowdevnotreal** [comment]
Thank goodness. 
I'm such an idiot and good at breaking things.....figured I struck again.
Even reverted my entire dev environment.....much appreciated for getting back to me on this.

I'm THE worst developer but I'm trying to be somewhere between a script kid and coder....a Scroder? Coscribble?
I'm still testing names.
I'll come up with a good one eventually.

Your main menu has an option that is in my code I'm not releasing yet.....I'm working on a pure OSINT automation, and my opening menu is:
Corporate or individual..  literally. 

Not sure why I'm wasting time developing this app anymore after seeing what you made.....ugh.

Appreciate a heads up when you do figure it out.
I'm switching gears on my project and since nothing like it exists I guess I'll keep plugging away at it.
Dog had a seizure, my life suck, got to go, thanks.
-Michael not a dev

**Comment by whiterabb17** [comment]
Sorry to hear,
And breaking your environment is always how it starts.
You'll get there, we all broke things at first

**Comment by whiterabb17** [comment]
Mine is fairly old, anything made after would more then likely use newer more updated tools.
So its always worthwhile. I also dont really dev this anymore. 
So new is good

**Comment by shadowdevnotreal** [comment]
LOL, I meant I reverted the dev environment to make sure it wasnt me, but now that I know the repos were messed up....I will just wait.
TY for the response. Makes me feel good to know it was not something I did personally. It gave messages saying things were missing, but I am new to developing and error reporting.
