### ISSUE TITLE
Package installation issues

### ISSUE THREAD

**Issue by clairelim-cf** [whiterabb17/sifter#2]
when installing the package and running the install.sh -- the packages are not installed properly

install.sh: line 128: figlet: command not found

**Comment by whiterabb17** [comment]
so then install figlet using your package manager.

**Comment by clairelim-cf** [comment]
sorry copied the wrong part it asks me to authenticate and fails auth when i keyed in the right user and pw for github

```
Checking for Rapidscan
Cloning into 'rapidscan'...
Username for 'https://github.com': clairelim-cf
Password for 'https://clairelim-cf@github.com': 
remote: Support for password authentication was removed on August 13, 2021.
remote: Please see https://docs.github.com/en/get-started/getting-started-with-git/about-remote-repositories#cloning-with-https-urls for information on currently recommended modes of authentication.
fatal: Authentication failed for 'https://github.com/s1l3nt78/rapidscan.git/'
install.sh: line 239: cd: rapidscan: No such file or directory
chmod: cannot access 'rapidscan.py': No such file or directory
chmod: cannot access 'rapidscan': No such file or directory
mv: cannot stat 'rapidscan': No such file or directory
```

**Comment by whiterabb17** [comment]
Yes some repositories have moved, and some are no longer available. 

For any asking for authentication are no longer situated at the repository used when I create this tool. 
Just press enter for user and pass and continue with install
